# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='comms.proto',
  package='',
  syntax='proto2',
  serialized_options=b'B\005Comms',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63omms.proto\"@\n\tbroadcast\x12\x13\n\x0bMessageType\x18\x01 \x02(\t\x12\x10\n\x08Username\x18\x02 \x02(\t\x12\x0c\n\x04\x44\x61ta\x18\x03 \x02(\tB\x07\x42\x05\x43omms'
)




_BROADCAST = _descriptor.Descriptor(
  name='broadcast',
  full_name='broadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='MessageType', full_name='broadcast.MessageType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Username', full_name='broadcast.Username', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Data', full_name='broadcast.Data', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['broadcast'] = _BROADCAST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

broadcast = _reflection.GeneratedProtocolMessageType('broadcast', (_message.Message,), {
  'DESCRIPTOR' : _BROADCAST,
  '__module__' : 'comms_pb2'
  # @@protoc_insertion_point(class_scope:broadcast)
  })
_sym_db.RegisterMessage(broadcast)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
